### ISSUE TITLE
Groß- Kleinschreibung als Problem

### ISSUE THREAD

**Issue by aaabdulkarim** [TGM-HIT/sew9-2425-worttrainer-rmartin69420#1]
Beim Ausprobieren des WortTrainers, wurde die kleingeschriebene Version vom WortEintrag "Mann" nicht akzeptiert. Generell wäre es besser wenn die Groß- und Kleinschreibung bei jedem Wort ignoriert wird.

**Comment by rmartin69420** [comment]
gefixt!
